SELECT COMPANY.COMPANY_CODE, COMPANY.FOUNDER, 
    COUNT(DISTINCT LEAD_MANAGER.LEAD_MANAGER_CODE), 
    COUNT(DISTINCT SENIOR_MANAGER.SENIOR_MANAGER_CODE), 
    COUNT(DISTINCT MANAGER.MANAGER_CODE), 
    COUNT(DISTINCT EMPLOYEE.EMPLOYEE_CODE) 
FROM COMPANY, LEAD_MANAGER, SENIOR_MANAGER, MANAGER, EMPLOYEE 
    WHERE COMPANY.COMPANY_CODE = LEAD_MANAGER.COMPANY_CODE 
        AND LEAD_MANAGER.LEAD_MANAGER_CODE = SENIOR_MANAGER.LEAD_MANAGER_CODE 
        AND SENIOR_MANAGER.SENIOR_MANAGER_CODE = MANAGER.SENIOR_MANAGER_CODE
        AND MANAGER.MANAGER_CODE = EMPLOYEE.MANAGER_CODE
    GROUP BY COMPANY.COMPANY_CODE, COMPANY.FOUNDER
ORDER BY COMPANY.COMPANY_CODE;


